/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realestate;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Madhaba Patra
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("OPEN REAL ESTATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("REPAIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realestate/icons/real-estate-seo-expert.gif"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HomePage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
           try{  
Class.forName("com.mysql.jdbc.Driver");  
Connection con=DriverManager.getConnection(  
"jdbc:mysql://localhost:3306/RealEstate","root","123456");  
			Statement st = con.createStatement();
			int a,b,c,d,e,f,g,h,i;
				String app = "CREATE TABLE APPARTDB (APPID BIGINT (4) UNIQUE NOT NULL,APPNM VARCHAR (18) NOT NULL,APPSZ VARCHAR (10) NOT NULL,CITY VARCHAR (18) NOT NULL,APPPR BIGINT (18) NOT NULL,APPDESP VARCHAR (25),dobooking DATE,Booked INT (3))";
				String land="CREATE TABLE LANDDB (LANDID BIGINT (4) UNIQUE NOT NULL,LANDNM VARCHAR (18) NOT NULL,LANDSZ VARCHAR (10) NOT NULL,CITY VARCHAR (18) NOT NULL,LANDPR BIGINT (18) NOT NULL,LANDDESP VARCHAR (25),dobooking DATE,Booked INT (3))";
                                     String office="CREATE TABLE OFFICE (OFFID BIGINT (4) UNIQUE NOT NULL,OFFNM VARCHAR (18) NOT NULL,OFFSZ VARCHAR (10) NOT NULL,CITY VARCHAR (18) NOT NULL,OFFPR BIGINT (18) NOT NULL,OFFDESP VARCHAR (25),dobooking DATE,Booked INT (3))";
                                     String house="CREATE TABLE HOUSE (HID BIGINT (4) UNIQUE NOT NULL,HNM VARCHAR (18) NOT NULL,HSZ VARCHAR (10) NOT NULL,CITY VARCHAR (18) NOT NULL,HPR BIGINT (18) NOT NULL,HDESP VARCHAR (25),dobooking DATE,Booked INT (3))";
                                     String booking="CREATE TABLE BOOKING (LOGID VARCHAR (18) NOT NULL,RESRC VARCHAR (18) NOT NULL,RESRCID BIGINT (4) NOT NULL UNIQUE ,PAY BIGINT (18) NOT NULL, dobooking DATE NOT NULL)";
                                     String login="CREATE TABLE LOGIN(LOGID VARCHAR (18) UNIQUE,PWD VARCHAR (18), PROFILE VARCHAR (18), DOB DATE,PHN BIGint (18))";
                                     String post="CREATE TABLE postrequirement (SLNO BIGINT (4) ,TRANSTYPE VARCHAR (4), PROPTYPE VARCHAR (10),CITY  VARCHAR (18) NOT NULL,ADDR  VARCHAR (18) NOT NULL,DESP VARCHAR (24) NOT NULL,BUDG BIGINT (10) NOT NULL,ESMTIME VARCHAR (18),NAME VARCHAR (18) NOT NULL,PHN BIGint (18) NOT NULL)";
                                     String register="CREATE TABLE REGISTER(REGID BIGINT (4) UNIQUE,PROFILE VARCHAR (18), NAME VARCHAR (18) NOT NULL, FNAME VARCHAR (18) NOT NULL, CITY VARCHAR (18) NOT NULL, SEX VARCHAR (2) NOT NULL, PHN BIGint (18) NOT NULL UNIQUE,DOB DATE NOT NULL,PWD VARCHAR (18) NOT NULL)";
                                     String contactus="CREATE TABLE CONTACTUS(NAME VARCHAR (18) NOT NULL, PHN BIGint (18) not null,City Varchar (18), SUBJECT VARCHAR (18), MSG VARCHAR (36) NOT NULL)";
                       a=st.executeUpdate(app);
                       b=st.executeUpdate(land);
                        c=st.executeUpdate(office);
                         d=st.executeUpdate(house);
                          e=st.executeUpdate(booking);
                           f=st.executeUpdate(login);
                            g=st.executeUpdate(contactus);
                             h=st.executeUpdate(register);
                              i=st.executeUpdate(post);
		
			st.close();
			con.close();
jLabel3.setText("repaired");
		} catch (Exception e3) {
                    int rr2 = JOptionPane.showConfirmDialog(this, e3.getMessage(),
					"already tables ~ created ", 0, 1);
			jLabel3.setText("some error go to database system");
		}
		
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
